# Generated by Django 3.0.7 on 2020-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
