# Generated by Django 3.0.7 on 2020-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profapp', '0002_auto_20200622_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='default.png'),
        ),
    ]
