# Generated by Django 3.0.7 on 2020-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('location', models.CharField(default='', max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('target_amount', models.PositiveIntegerField()),
                ('beneficiary', models.CharField(default='', max_length=70)),
                ('donors', models.CharField(default='', max_length=70)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
