# Generated by Django 3.0.7 on 2020-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='number',
            new_name='card_number',
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
