# Generated by Django 3.0.7 on 2020-06-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('location', models.CharField(default='', max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('target_amount', models.PositiveIntegerField()),
                ('beneficiary', models.CharField(default='', max_length=70)),
                ('donors', models.CharField(blank=True, max_length=70)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(null=True)),
                ('organization', models.CharField(max_length=250, null=True)),
                ('phone_number', models.IntegerField(default=None)),
                ('card_number', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
