# Generated by Django 3.0.7 on 2020-06-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0002_category_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
