# Generated by Django 3.0.7 on 2020-06-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0002_auto_20200622_0418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
