# Generated by Django 3.0.7 on 2020-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dona', '0003_auto_20200619_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
