# Generated by Django 3.0.7 on 2020-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0004_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(null=True)),
                ('organization', models.CharField(max_length=250, null=True)),
                ('phone_number', models.IntegerField(default=None)),
                ('card_number', models.IntegerField(default=None)),
            ],
        ),
    ]
