# Generated by Django 3.0.7 on 2020-06-22 13:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0007_charity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='charity',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
