# Generated by Django 3.0.7 on 2020-06-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=70)),
                ('target_amount', models.PositiveIntegerField(default='1')),
                ('amount_raised', models.PositiveIntegerField(blank=True, default='1')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('story_image', models.ImageField(blank=True, upload_to='story/')),
                ('location', models.CharField(max_length=20)),
                ('charity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dona.Charity')),
            ],
        ),
    ]
