# Generated by Django 3.0.7 on 2020-06-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0002_auto_20200629_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryMini',
        ),
    ]
