# Generated by Django 3.0.7 on 2020-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0003_delete_storymini'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, upload_to='story/'),
        ),
    ]
