# Generated by Django 3.0.7 on 2020-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0004_story_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_image',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
