# Generated by Django 3.0.7 on 2020-06-30 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0005_auto_20200630_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
