# Generated by Django 3.0.7 on 2020-06-30 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0006_story_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image_name',
        ),
        migrations.AddField(
            model_name='story',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
