# Generated by Django 3.0.7 on 2020-06-30 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0007_auto_20200630_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='file',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
