# Generated by Django 3.0.7 on 2020-06-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0008_auto_20200630_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image_name',
        ),
    ]
