# Generated by Django 3.0.7 on 2020-06-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0009_remove_story_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='user',
            new_name='user_id',
        ),
    ]
