# Generated by Django 3.0.7 on 2020-06-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0010_auto_20200630_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='user_id',
            new_name='user',
        ),
    ]
