# Generated by Django 3.0.7 on 2020-06-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dona', '0011_auto_20200630_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
